### ISSUE TITLE
TODO General

### ISSUE THREAD

**Issue by cloverich** [cloverich/chronicle#14]
While Prototyping, I just need a todo list:

- [x] Logs should display the topic name, not the id
- [x] Make it a chrome App  
-  [x] ~~Use a join table for Many to Many~~ ~~The join table can be re-constructed from the individually output files~~  Be stupid and make everything an event 
- [x] Filesystem --> One big data dump
- [ ] Images --> Probably ready for a separate issue at that point
- [x] Use Promises in all store responses
- [x] Consistency: `DayLog` --> Log. Log has many *entries*. DayLog is no longer necessary.
- [x] Research how foreign key relationships are handled in document db's. [1](https://www.firebase.com/blog/2013-04-12-denormalizing-is-normal.html) 
- [x] Need a `/topics` list
- [x] Should be able to add to `/topics` at will
- [x] ~~Creating a topic when a log does not exist should create a log for that day with no content~~
- [x] Updating logs with a new topic does not live update logs list -- it needs a change listener

At the end, when the core functions are there:
- [ ] Back-up old issues
- [ ] Migrate old logs and topics to IndexedDb
- [ ] Add backup functions to new system
- [x] Commit before doing the refactor work -- to have a saved reference
- [x] Refactor 
- [ ] Flux
- [x] Database Promises

Notes:
- Compound Queries: 
http://stackoverflow.com/questions/12084177/in-indexeddb-is-there-a-way-to-make-a-sorted-compound-query
http://stackoverflow.com/questions/6405650/how-do-i-query-using-multiple-conditions-in-indexeddb?lq=1
